services:
  texlive:
    build:
      context: .
      dockerfile: Dockerfile
      environment:
        - TZ=Asia/Tokyo
      args:
        USERNAME: $USER
        UID: $UID
        GID: $GID
    volumes:
      - ..:/workspace
    tty: true
    stdin_open: true
