services:
  texlive:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: $USER
        UID: 1000
        GID: 1000
    volumes:
      - ..:/workspace
    tty: true
    stdin_open: true
