services:
  texlive:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: $USER
        UID: $UID
        GID: $GID
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ..:/workspace
    tty: true
    stdin_open: true
